name: Deployment

concurrency:
  group: production

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout le code source
      uses: actions/checkout@v3

    - name: Copier les fichiers vers le répertoire du site web
      run: |
        rsync -av --delete-after ${{ github.workspace }}/ /var/www/portfolio/
      env:
        SITE_PATH: /var/www/portfolio/

    - name: Redémarrer Nginx
      run: |
        sudo systemctl restart nginx
